version: '3'
services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/traefik.toml
      - ./traefik/acme.json:/acme.json
    networks:
      - web
    depends_on:
      - kibana
      - apm-server

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    restart: always
    container_name: elasticsearch
    environment:
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - eak

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    restart: always
    container_name: kibana
    networks:
      - eak
    depends_on:
      - elasticsearch
    labels:
      - "traefik.backend=kibana"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:kibana.eak.org"
      - "traefik.enable=true"
      - "traefik.port=5601"
      - "traefik.default.protocol=https"
      - "traefik.admin.frontend.rule=Host:admin.eak.org"
      - "traefik.admin.protocol=https"
      - "traefik.admin.port=9443"

  apm-server:
    image: docker.elastic.co/apm/apm-server:6.2.2
    restart: always
    container_name: apm-server
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    networks:
      - eak
      - web
    depends_on:
      - elasticsearch
    labels:
      - "traefik.backend=apm"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:apm.eak.org"
      - "traefik.enable=true"
      - "traefik.port=8200"
      - "traefik.default.protocol=https"
      - "traefik.admin.frontend.rule=Host:admin.eak.org"
      - "traefik.admin.protocol=https"
      - "traefik.admin.port=9443"

  beats:
    image: docker.elastic.co/beats/metricbeat:6.2.2
    command:
      - "-system.hostfs=/hostfs"
    container_name: beats
    user: root
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - eak
    depends_on:
      - elasticsearch

volumes:
  esdata:

networks:
  eak:
  web: